# Site settings
# These are used to personalize your new site.
title: Kevin Holmes # your name here
logo: "/images/csu_profile_pic.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Technology
repository: "codersc/codersc.github.io"
github_username:  codersc # update with your username

# Build setting
theme: jekyll-theme-minimal

